version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://mock-backend:4000
    depends_on:
      - mock-backend

  mock-backend:
    image: kennethreitz/httpbin
    ports:
      - "4000:80" 