version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:myDB123@db/meal_plan_db2
      - SECRET_KEY=a492864c8d3f5e9b7a1c6d0e2b4f8a1937c5e9d2b4f8c1a6e3d7b9f2e5a8c4d
      - OPENAI_API_KEY=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
      - DEBUG=False
      - PORT=8000
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_ENV=development
      - REACT_APP_ENABLE_AUTH=true
      - REACT_APP_ENABLE_MEAL_PLANNER=true
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=myDB123
      - POSTGRES_DB=meal_plan_db2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: 