version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=production
        - REACT_APP_API_URL=https://smartfuel-backend.up.railway.app
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 3s
      retries: 3 